import React, { useMemo } from 'react'
import TableContainer from '../../components/TableComponent'
import { Row, Card, CardBody, CardTitle, Container, Button } from 'reactstrap'
import UsersTableComponent from '../../components/UserTableComponent'

const usersData = [
  {
    id: 0,
    user: 'John Doe',
    userType: 'Guest',
    totalPayments: '1234',
    comissions: '345',
    SuccessfulPayments: '2',
    FailedPayments: '1',
    PaymentHistory: 'helo',
    status: 'Pending',
    _props: { color: 'primary', align: 'middle' },
  },
  {
    id: 1,
    user: 'John',
    userType: 'seeker',
    totalPayments: '1034',
    comissions: '34',
    SuccessfulPayments: '10',
    FailedPayments: '5',
    PaymentHistory: 'sample',
    status: 'Done',
    _cellProps: { all: { className: 'fw-semibold' }, name: { color: 'info' } },
  },
  {
    id: 2,
    user: 'Jane Smith',
    userType: 'Member',
    totalPayments: '2045',
    comissions: '400',
    SuccessfulPayments: '5',
    FailedPayments: '2',
    PaymentHistory: 'history1',
    status: 'Active',
  },
  {
    id: 3,
    user: 'Alice Johnson',
    userType: 'Guest',
    totalPayments: '1500',
    comissions: '100',
    SuccessfulPayments: '3',
    FailedPayments: '1',
    PaymentHistory: 'history2',
    status: 'Pending',
  },
  {
    id: 4,
    user: 'Bob Brown',
    userType: 'Admin',
    totalPayments: '3000',
    comissions: '600',
    SuccessfulPayments: '6',
    FailedPayments: '0',
    PaymentHistory: 'history3',
    status: 'Active',
  },
  {
    id: 5,
    user: 'Charlie Green',
    userType: 'Staff',
    totalPayments: '1000',
    comissions: '50',
    SuccessfulPayments: '1',
    FailedPayments: '1',
    PaymentHistory: 'history4',
    status: 'Inactive',
  },
  {
    id: 6,
    user: 'David White',
    userType: 'Member',
    totalPayments: '2500',
    comissions: '200',
    SuccessfulPayments: '4',
    FailedPayments: '2',
    PaymentHistory: 'history5',
    status: 'Pending',
  },
  {
    id: 7,
    user: 'Emma Black',
    userType: 'Guest',
    totalPayments: '500',
    comissions: '10',
    SuccessfulPayments: '0',
    FailedPayments: '1',
    PaymentHistory: 'history6',
    status: 'Banned',
  },
  {
    id: 8,
    user: 'Frank Blue',
    userType: 'Admin',
    totalPayments: '4500',
    comissions: '700',
    SuccessfulPayments: '9',
    FailedPayments: '1',
    PaymentHistory: 'history7',
    status: 'Active',
  },
  {
    id: 9,
    user: 'Grace Yellow',
    userType: 'Staff',
    totalPayments: '600',
    comissions: '30',
    SuccessfulPayments: '2',
    FailedPayments: '0',
    PaymentHistory: 'history8',
    status: 'Done',
  },
  {
    id: 10,
    user: 'Hannah Red',
    userType: 'Member',
    totalPayments: '1700',
    comissions: '150',
    SuccessfulPayments: '3',
    FailedPayments: '1',
    PaymentHistory: 'history9',
    status: 'Pending',
  },
  {
    id: 11,
    user: 'Ian Purple',
    userType: 'Guest',
    totalPayments: '2000',
    comissions: '100',
    SuccessfulPayments: '5',
    FailedPayments: '3',
    PaymentHistory: 'history10',
    status: 'Active',
  },
  {
    id: 12,
    user: 'Jack Orange',
    userType: 'Admin',
    totalPayments: '3500',
    comissions: '400',
    SuccessfulPayments: '7',
    FailedPayments: '1',
    PaymentHistory: 'history11',
    status: 'Banned',
  },
  {
    id: 13,
    user: 'Kathy Pink',
    userType: 'Staff',
    totalPayments: '800',
    comissions: '60',
    SuccessfulPayments: '1',
    FailedPayments: '1',
    PaymentHistory: 'history12',
    status: 'Pending',
  },
  {
    id: 14,
    user: 'Liam Gold',
    userType: 'Member',
    totalPayments: '2200',
    comissions: '300',
    SuccessfulPayments: '4',
    FailedPayments: '2',
    PaymentHistory: 'history13',
    status: 'Done',
  },
  {
    id: 15,
    user: 'Mia Silver',
    userType: 'Guest',
    totalPayments: '1300',
    comissions: '70',
    SuccessfulPayments: '2',
    FailedPayments: '1',
    PaymentHistory: 'history14',
    status: 'Active',
  },
  {
    id: 16,
    user: 'Noah Bronze',
    userType: 'Admin',
    totalPayments: '4000',
    comissions: '500',
    SuccessfulPayments: '8',
    FailedPayments: '0',
    PaymentHistory: 'history15',
    status: 'Inactive',
  },
  {
    id: 17,
    user: 'Olivia Platinum',
    userType: 'Staff',
    totalPayments: '950',
    comissions: '20',
    SuccessfulPayments: '2',
    FailedPayments: '1',
    PaymentHistory: 'history16',
    status: 'Pending',
  },
  {
    id: 18,
    user: 'Paul Copper',
    userType: 'Member',
    totalPayments: '1600',
    comissions: '100',
    SuccessfulPayments: '3',
    FailedPayments: '2',
    PaymentHistory: 'history17',
    status: 'Done',
  },
  {
    id: 19,
    user: 'Quinn Diamond',
    userType: 'Guest',
    totalPayments: '2300',
    comissions: '150',
    SuccessfulPayments: '4',
    FailedPayments: '0',
    PaymentHistory: 'history18',
    status: 'Active',
  },
  {
    id: 20,
    user: 'Ryan Jade',
    userType: 'Admin',
    totalPayments: '4800',
    comissions: '600',
    SuccessfulPayments: '9',
    FailedPayments: '1',
    PaymentHistory: 'history19',
    status: 'Pending',
  },
  {
    id: 21,
    user: 'Sophia Emerald',
    userType: 'Staff',
    totalPayments: '1100',
    comissions: '30',
    SuccessfulPayments: '2',
    FailedPayments: '0',
    PaymentHistory: 'history20',
    status: 'Inactive',
  },
  {
    id: 22,
    user: 'Tom Sapphire',
    userType: 'Member',
    totalPayments: '1400',
    comissions: '100',
    SuccessfulPayments: '3',
    FailedPayments: '1',
    PaymentHistory: 'history21',
    status: 'Pending',
  },
  {
    id: 23,
    user: 'Uma Ruby',
    userType: 'Guest',
    totalPayments: '2100',
    comissions: '200',
    SuccessfulPayments: '4',
    FailedPayments: '2',
    PaymentHistory: 'history22',
    status: 'Active',
  },
  {
    id: 24,
    user: 'Victor Opal',
    userType: 'Admin',
    totalPayments: '2600',
    comissions: '300',
    SuccessfulPayments: '5',
    FailedPayments: '1',
    PaymentHistory: 'history23',
    status: 'Banned',
  },
  {
    id: 25,
    user: 'Wendy Topaz',
    userType: 'Staff',
    totalPayments: '900',
    comissions: '40',
    SuccessfulPayments: '1',
    FailedPayments: '1',
    PaymentHistory: 'history24',
    status: 'Pending',
  },
  {
    id: 26,
    user: 'Xander Pearl',
    userType: 'Member',
    totalPayments: '1700',
    comissions: '150',
    SuccessfulPayments: '3',
    FailedPayments: '1',
    PaymentHistory: 'history25',
    status: 'Done',
  },
  {
    id: 27,
    user: 'Yara Amber',
    userType: 'Guest',
    totalPayments: '2300',
    comissions: '120',
    SuccessfulPayments: '4',
    FailedPayments: '1',
    PaymentHistory: 'history26',
    status: 'Active',
  },
  {
    id: 28,
    user: 'Zach Onyx',
    userType: 'Admin',
    totalPayments: '3000',
    comissions: '400',
    SuccessfulPayments: '6',
    FailedPayments: '0',
    PaymentHistory: 'history27',
    status: 'Inactive',
  },
  {
    id: 29,
    user: 'Amy Quartz',
    userType: 'Staff',
    totalPayments: '1000',
    comissions: '50',
    SuccessfulPayments: '1',
    FailedPayments: '1',
    PaymentHistory: 'history28',
    status: 'Pending',
  },
  {
    id: 30,
    user: 'Ben Citrine',
    userType: 'Member',
    totalPayments: '2100',
    comissions: '100',
    SuccessfulPayments: '4',
    FailedPayments: '1',
    PaymentHistory: 'history29',
    status: 'Done',
  },
  {
    id: 31,
    user: 'Cara Aquamarine',
    userType: 'Guest',
    totalPayments: '1250',
    comissions: '75',
    SuccessfulPayments: '2',
    FailedPayments: '2',
    PaymentHistory: 'history30',
    status: 'Active',
  }
]

function AccountDetails() {
  // Dummy data for the table
  const data = [
    {
      user: 'Joe',
      userType: 'Seeker',
      ipoNo: 'PO001',
      date: '2024-01-15',
      supplier: 'demo A',
      process: 'Process 1',
      soNo: 'SO123',
    },
    {
      user: 'Cena',
      userType: 'Provider',
      ipoNo: 'PO001',
      date: '2024-01-15',
      supplier: 'demo A',
      process: 'Process 1',
      soNo: 'SO123',
    },
    {
      user: 'Joe',
      userType: 'Seeker',
      ipoNo: 'PO001',
      date: '2024-01-15',
      supplier: 'demo A',
      process: 'Process 1',
      soNo: 'SO123',
    },
    {
      user: 'Cena',
      userType: 'Provider',
      ipoNo: 'PO001',
      date: '2024-01-15',
      supplier: 'demo A',
      process: 'Process 1',
      soNo: 'SO123',
    },
    // Add more data as needed
  ]

  const columns = useMemo(
    () => [
      {
        Header: 'User',
        accessor: 'user',
        filter: 'text',
      },
      {
        Header: 'User Type',
        accessor: 'userType',
        filter: 'text',
      },
      {
        Header: 'Total Payments',
        accessor: 'ipoNo',
        filter: 'text',
      },
      {
        Header: 'Commissions',
        accessor: 'date',
        filter: 'text',
      },
      {
        Header: 'Successful Payments',
        accessor: 'supplier',
        filter: 'text',
      },
      {
        Header: 'Failed Payments',
        accessor: 'soNo',
        filter: 'text',
      },
      {
        Header: 'Payment History',
        accessor: '',
        Cell: () => <Button color="primary">View</Button>,
      },
    ],
    [],
  )

  return (
    <Container fluid={true}>
      <Row>
        <CardTitle className="mb-4 text">ACCOUNTS DETAILS</CardTitle>
        <Card>
          <CardBody>
            {/* <TableContainer
              columns={columns}
              data={data}
              isGlobalFilter={true}
              isAddOptions={false}
              isJobListGlobalFilter={true}
              isPagination={true}
              iscustomPageSizeOptions={true}
              isShowingPageLength={true}
              customPageSize={5}
              tableClass="table-bordered align-middle nowrap mt-2"
              paginationDiv="col-sm-12 col-md-7"
              pagination="pagination justify-content-end pagination-rounded"
            /> */}
            <UsersTableComponent usersData={usersData} />
          </CardBody>
        </Card>
      </Row>
    </Container>
  )
}

export default AccountDetails
